### ISSUE TITLE
Of potential args and kwargs

### ISSUE THREAD

**Issue by nstarman** [jobovy/galpy#437] opened 2020-11-19 17:17 UTC
When calling a `Potential` with Quantity arguments, the conversion wrappers fail if all args are used and not everything has a unit of kpc, or if all kwargs are used, in which case no unit conversion happens.

For instance

```python
hernquist_pot(hernquist_samples.cylindrical.rho,
                 hernquist_samples.cylindrical.z,
                 hernquist_samples.cylindrical.phi)
```
fails with 
```
galpy/util/conversion.py in wrapper(*args, **kwargs)
    863         for ii in range(1,len(args)):
    864             if _APY_LOADED and isinstance(args[ii],units.Quantity):
--> 865                 newargs= newargs+(args[ii].to(units.kpc).value/ro,)
    866             else:
    867                 newargs= newargs+(args[ii],)
```

Since ``phi`` is in degrees.

Alternative,

```
hernquist_pot(R=hernquist_samples.cylindrical.rho,
                z=hernquist_samples.cylindrical.z,
                 phi=hernquist_samples.cylindrical.phi)
```

Also fails since R, z are not args and are not unit converted.

I haven't looked into this case specifically, but a general solution I'm familiar with is to construct an `inspect.signature` in the wrapper constructor (so as not to make a new one each time) and then create a ``BoundArguments`` in `wrapper` to use on the wrapped function.

**Comment by jobovy** [comment] 2020-11-21 01:43
I don't quite understand what the issue is here, is the issue that you are passing `R` and `z` without units and `phi` with units? I'm moving towards not allowing *any* non-Quantity inputs, so I'm not keen on supporting mixing Quantities and internal units... Just convert phi to radian if that's the issue (`phi.to_value(units.rad)`).

**Comment by nstarman** [comment] 2020-11-21 06:00
The problem is that the decorator distinguishes between args and kwargs in a different way than python. In the first example, all the inputs were arguments, when ``phi`` is "meant" to be a kwarg. Consequently the wrapper tries to convert it to kpc. The reverse is true for the second example, where ``R`` and ``z`` are kwargs and therefore NOT converted by the wrapper.

**Comment by jobovy** [comment] 2020-11-25 00:53
Oh I see. Yeah, the docs are pretty clear I think that phi is supposed to be a kwarg, so I don't consider this to be a bug. I don't know why python allows arguments to be provided as keyword arguments, but that's not supported use of the code. Unfortunately, python doesn't provide an easy way to turn this off.

**Closed by jobovy** 2020-11-25 00:53 UTC

**Comment by nstarman** [comment] 2020-11-25 01:58
If phi should only be a kwarg, that can be forced with the signature

```
def func(R, z, *, phi=0):
    ...
```

**Comment by jobovy** [comment] 2020-11-25 02:22
Guess that should go on the list for when I fully drop any Python 2 support, because that doesn't work in Python 2.
