### ISSUE TITLE
compiler/install problem

### ISSUE THREAD

**Issue by lmwidrow** [jobovy/galpy#310] opened 2017-07-22 17:16 UTC
This screen shot is from a failed attempt to install galpy.  I'm using Mac OS10.12.3 with clang version  Apple LLVM version 8.1.0 (clang-802.0.42).  The install was attempted without openmp using

pip install -U --no-deps --install-option="--no-openmp" git+git://github.com/jobovy/galpy.git#egg=galpy

a screen shot from the install attempt is shown here:

![screen shot 2017-07-22 at 12 11 44 pm](https://user-images.githubusercontent.com/24191740/28493178-dc67091c-6edf-11e7-8ca7-2b865adc53b9.png)

**Comment by jobovy** [comment] 2017-07-22 17:58
Thanks for reporting this. I think this is related to how the ``interrupted`` variable is defined in the C code (this variable allows the orbit integration to be interrupted when running in C). I've checked in a possible fix in the branch ``fix310``, could you try using that? (I can't reproduce the error). I think this should work to install from this branch
```
pip install -U --no-deps --install-option="--no-openmp" git+git://github.com/jobovy/galpy.git@fix310
```

**Comment by lmwidrow** [comment] 2017-07-23 12:04
Thanks.  Install now works!

**Comment by jobovy** [comment] 2017-07-23 14:49
Great, glad it worked!

**Closed** 2017-07-23 16:23 UTC
Labels: compilation bug
