### ISSUE TITLE
.pyd image not found

### ISSUE THREAD

**Issue by senorPepe** [jobovy/galpy#337] opened 2018-04-17 08:34 UTC
Dear Jo,

I recently downloaded and installed GalPy for a university project. However, I get the following warnings when running the examples from your paper. I do not know how to solve this and what to do next. Hope you can help, thanks in advance!

Ps. This is from running figure 21:
galpyWarning: interppotential_c extension module not loaded, because galpy_interppotential_c.cp36-win_amd64.pyd image was not found
galpyWarning: integratePlanarOrbit_c extension module not loaded, because galpy_integrate_c.cp36-win_amd64.pyd image was not found
galpyWarning: integrateFullOrbit_c extension module not loaded, because galpy_integrate_c.cp36-win_amd64.pyd image was not found
galpyWarning: actionAngleAdiabatic_c extension module not loaded, because galpy_actionAngle_c.cp36-win_amd64.pyd image was not found
galpyWarning: actionAngleStaeckel_c extension module not loaded, because galpy_actionAngle_c.cp36-win_amd64.pyd image was not found

**Comment by jobovy** [comment] 2018-04-17 14:13
Hi,

It seems like you are on a Windows system? If you installed the ``conda`` or ``pip`` version of the code, these warnings are expected, because the C extensions were not properly compiled in the latest version. Depending on what you want to do with the code, these warnings may be unimportant (almost all of the code still works, it just won't be as fast).

The latest ``master`` version of the code can now actually be compiled on Windows, I finally fixed this after the latest release. See [this section of the documentation](http://galpy.readthedocs.io/en/latest/installation.html#installing-from-source-on-windows) for instructions on how to do that. Note that compiling code on Windows can be quite difficult if you haven't done it before.

**Comment by henrysky** [comment] 2018-04-19 03:05
Here are two galpy wheels I have built if you have difficulty: galpy 1.3 (27 Feb 2018) and galpy 1.4dev (18 April 2018) you can use for Win64 py36

**Use with caution as I am not doing any serious thing with galpy and I will not guarantee the wheels I built work correctly**
https://drive.google.com/drive/folders/1tai7diGXywauP4Sn-_qVUg_SMkTAiey0

**Comment by senorPepe** [comment] 2018-04-24 07:37
Thank you both! However, it still not works. Firstly, I cannot seem to ignore the warnings as suggested by mr. Bovy. 
And secondly, using the wheels henrysky built, I get the following error:
Python\lib\site-packages\astropy\coordinates\sky_coordinate.py:1558: AstropyDeprecationWarning: Passing a frame as a positional argument is now deprecated, use the frame= keyword argument instead.
  "instead.", AstropyDeprecationWarning)

I (once again) do not know what to do.

Thank you in advance!

**Comment by jobovy** [comment] 2018-04-24 15:20
What code are you trying to run when you get the ``AstropyDeprecationWarning``? Please post the full error message.

Note also that that's just a warning, the code should work fine, so I think you're good?

**Comment by senorPepe** [comment] 2018-04-24 15:27
I tried to ignore the warning, but that was unsuccessful, I tried the command -W"ignore", which should work according to the internet ;). Any suggestions?
The AstropyDeprecationWarning happened after running figure 21 from you paper in the wheel henrysky built.

**Comment by jobovy** [comment] 2018-04-24 15:32
Please post the actual code and the full error message, that way I can see exactly which line has the issue.

What do you mean by "that was unsuccessful"? Again, it's just a deprecation warning about a feature being removed in a future version of astropy, the feature should still work fine.

**Comment by henrysky** [comment] 2018-04-24 18:43
@senorPepe I am using Anaconda 5.1 py36 win64, I cannot reproduce the warning with my wheels with both astropy 2.0.3 & 3.0.2 if you are referring to figure 21 here: https://github.com/jobovy/galpy-paper-figures.

**Comment by henrysky** [comment] 2018-05-11 23:13
@senorPepe Jo updated `galpy` to fix the `AstropyDeprecationWarning` and we have updated `galpy` so that you can compile `galpy` with `OpenMP` on Windows (which has great speedup for some functions), see #339 and instruction on how to compile `galpy` on Windows: http://galpy.readthedocs.io/en/latest/installation.html#installing-from-source-on-windows

Moreover, I have compiled `galpy` with `OpenMP` yesterday with those fixes, so feel free to use it: https://drive.google.com/open?id=1TF7Kv961PNkxZjAuwHuRf2Bhu8-otohr

**Comment by jobovy** [comment] 2018-06-26 00:00
@senorPepe, do you still have an issue with this? If so, please re-open the issue; I'm closing it for now.

**Closed by jobovy** 2018-06-26 00:00 UTC
